set(__QT_DEPLOY_TARGET_SudokuSolver_FILE F:/Progetti_Qt/SudokuSolver/SudokuSolver.exe)
set(__QT_DEPLOY_TARGET_SudokuSolver_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_SudokuSolver_RUNTIME_DLLS F:/Qt/6.10.0/mingw_64/bin/Qt6Widgets.dll;F:/Progetti_Qt/SudokuSolver/liblibSudokuSolverAlgorithm.dll;F:/Qt/6.10.0/mingw_64/bin/Qt6Gui.dll;F:/Qt/6.10.0/mingw_64/bin/Qt6Core.dll)
set(__QT_DEPLOY_TARGET_libSudokuSolverAlgorithm_FILE F:/Progetti_Qt/SudokuSolver/liblibSudokuSolverAlgorithm.dll)
set(__QT_DEPLOY_TARGET_libSudokuSolverAlgorithm_TYPE SHARED_LIBRARY)
set(__QT_DEPLOY_TARGET_libSudokuSolverAlgorithm_RUNTIME_DLLS )
